--- 
title: "Data Analytics for the Public Good"
date: "Spring 2019"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
biblio-style: apalike
link-citations: no
description: "A course focused on data-driven practices for public sector organizations."
---



# Welcome {-}



> **DATA ANALYTICS FOR THE PUBLIC GOOD:**
>
> **Building Data-Driven Organizations in the Public and Nonprofit Sector**
>
> _**Watts College of Public Service and Community Solutions, Arizona State University**_


--- 

This collaborative text was created through efforts of students in the ASU course [PAF 586: Data for the Public Good](assets/Syllabus-PAF-586-Spring-2019.pdf). The class covers topics about the sources and uses of data in modern organizations, with goals of understanding management approaches to:

* Harness large-scale data to inform policy design, increase stakeholder engagement, and improve service delivery.
* Intelligently consider the social, political, and ethical considerations of data in the public sector. 

This text is meant to provide a broad overview of these topics, broken out into themes, with suggestions about how to best integrated new methods and best practices of data collection, management, and utlization. We draw heavily from the following texts:

1. Pentland, A. (2015). *Social Physics: How social networks can make us smarter.* Penguin. 
2. Meier, P. (2015). *Digital humanitarians: how big data is changing the face of humanitarian response.* Routledge.  
3. Eagle, N., & Greene, K. (2014). *Reality mining: Using big data to engineer a better world.* MIT Press.  
4. O'Neil, C. (2016). *Weapons of math destruction: How big data increases inequality and threatens democracy.* Broadway Books. 
5. Duhigg, C. (2016). *Smarter faster better: The secrets of being productive.* Random House. 
6. Sutherland, J., Sutherland, J. J. (2014). *Scrum: the art of doing twice the work in half the time.* 



# Authors {-}

The following students in the course have contributed the chapter summaries and best practice overviews. 


1. Lindsey Duncan 
1. Rachael Goodwin 
1. Erin Hart 
1. Thomas Kolwicz 
1. Carlos Lopez 
1. Joseph Lynch 
1. Julie Moore 
1. Marcela Morales 
1. Lorna Romero 
1. William Seeley 
1. Matthew Simon 
1. Dennis Stockwell 
1. Justin Stoker 
1. Lauren Zajac 


 









